# utils/embedder.py
#
# Handles all vector-store work: embedding text chunks and image description
# chunks via Voyage AI, then upserting everything into ChromaDB.
#
# Image descriptions (generated by utils/vision.py) are stored as their own
# searchable chunks with chunk_type="image" so they can be retrieved by
# semantic search just like text — and the actual image file is shown in the UI.

import hashlib
import json
import time
from typing import Callable

import chromadb
import voyageai

import config

# ── Constants ─────────────────────────────────────────────────────────────────
_EMBED_BATCH_SIZE = 32    # safe batch size for Voyage AI (max 128)
_RATE_LIMIT_PAUSE = 0.5   # seconds between embedding batches


# ── ChromaDB helpers ──────────────────────────────────────────────────────────

def _get_collection() -> chromadb.Collection:
    """Return (or create) the persistent ChromaDB collection on disk."""
    client = chromadb.PersistentClient(path=str(config.CHROMA_DIR))
    return client.get_or_create_collection(
        name=config.CHROMA_COLLECTION,
        metadata={"hnsw:space": "cosine"},
    )


def _stable_image_id(image_path: str) -> str:
    """
    Generate a deterministic chunk ID for an image based on its file path.
    This ensures re-committing the same image upserts (replaces) rather than
    creating a duplicate entry.
    """
    return "img_" + hashlib.md5(image_path.encode()).hexdigest()


def _embed_and_upsert(
    items: list[dict],
    collection: chromadb.Collection,
    voyage_client,
    progress_cb,
    progress_start: float,
    progress_end: float,
    label: str,
) -> int:
    """
    Shared helper: embed a list of items (each must have 'text', 'chunk_id',
    'metadata') in batches and upsert them into collection.
    Returns the number of items committed.
    """
    total     = len(items)
    committed = 0

    for batch_start in range(0, total, _EMBED_BATCH_SIZE):
        batch = items[batch_start : batch_start + _EMBED_BATCH_SIZE]
        texts = [item["text"] for item in batch]

        frac = progress_start + (progress_end - progress_start) * (batch_start / total)
        if progress_cb:
            end_idx = min(batch_start + len(batch), total)
            progress_cb(frac, f"{label} {batch_start + 1}–{end_idx} of {total}…")

        result     = voyage_client.embed(texts, model=config.VOYAGE_MODEL, input_type="document")
        embeddings = result.embeddings

        collection.upsert(
            ids        = [item["chunk_id"]  for item in batch],
            embeddings = embeddings,
            documents  = texts,
            metadatas  = [item["metadata"]  for item in batch],
        )

        committed += len(batch)
        if batch_start + _EMBED_BATCH_SIZE < total:
            time.sleep(_RATE_LIMIT_PAUSE)

    return committed


# ── Main public function ──────────────────────────────────────────────────────

def commit_chunks(
    edited_df,
    parsed_chunks: list[dict],
    progress_cb: Callable[[float, str], None] | None = None,
    classify_images: bool = True,
) -> dict:
    """
    Embed and store all 'keep' text chunks plus their associated images.

    Steps:
      1. Merge user edits from the DataFrame back onto the raw chunk metadata.
      2. Delete existing ChromaDB entries for the affected PDFs (idempotent).
      3. Embed text chunks in batches → upsert to ChromaDB.
      4. If classify_images=True: call Claude vision on each unique image,
         embed the descriptions, upsert as chunk_type="image" entries.

    Returns a dict: {"text_chunks": int, "image_chunks": int}
    """
    def _prog(frac: float, msg: str):
        if progress_cb:
            progress_cb(frac, msg)

    # ── Step 1: merge edits ───────────────────────────────────────────────────
    keep_chunks = []
    for i, (_, row) in enumerate(edited_df.iterrows()):
        if not row["keep"]:
            continue
        orig = parsed_chunks[i]
        keep_chunks.append({
            "chunk_id":    orig["chunk_id"],
            "source_pdf":  orig["source_pdf"],
            "page_number": orig["page_number"],
            "image_paths": orig["image_paths"],
            "text":        str(row["text"]),
            "tags":        str(row["tags"]),
        })

    if not keep_chunks:
        return {"text_chunks": 0, "image_chunks": 0}

    # ── Step 2: clear existing entries for these PDFs ─────────────────────────
    affected_pdfs = list({c["source_pdf"] for c in keep_chunks})
    _prog(0.02, f"Clearing old entries for {len(affected_pdfs)} PDF(s)…")
    collection = _get_collection()
    for pdf_name in affected_pdfs:
        existing = collection.get(where={"source_pdf": pdf_name}, include=[])
        if existing["ids"]:
            collection.delete(ids=existing["ids"])

    voyage_client = voyageai.Client(api_key=config.VOYAGE_API_KEY)

    # ── Step 3: embed text chunks ─────────────────────────────────────────────
    text_items = [
        {
            "chunk_id": c["chunk_id"],
            "text":     c["text"],
            "metadata": {
                "chunk_type":  "text",
                "source_pdf":  c["source_pdf"],
                "page_number": c["page_number"],
                "tags":        c["tags"],
                # Image paths attached to this page — used in Phase 4 sources panel
                "image_paths": json.dumps(c["image_paths"]),
            },
        }
        for c in keep_chunks
    ]

    text_committed = _embed_and_upsert(
        text_items, collection, voyage_client, progress_cb,
        progress_start=0.05, progress_end=0.50,
        label="Embedding text chunk",
    )
    _prog(0.50, f"Text chunks done ({text_committed}). Starting image classification…")

    # ── Step 4: classify and embed images ─────────────────────────────────────
    image_committed = 0

    if classify_images:
        # Collect unique images from the keep chunks (same image may appear on
        # multiple chunks that share a page — deduplicate by path).
        seen_paths: set[str] = set()
        unique_images: list[dict] = []
        for c in keep_chunks:
            for img_path in c["image_paths"]:
                if img_path not in seen_paths:
                    seen_paths.add(img_path)
                    unique_images.append({
                        "image_path":  img_path,
                        "source_pdf":  c["source_pdf"],
                        "page_number": c["page_number"],
                    })

        if unique_images:
            # Import here to avoid circular imports and keep vision optional
            from utils.vision import classify_images_batch

            def _vision_prog(frac: float, msg: str):
                # Map vision progress into the 0.50–0.88 window
                _prog(0.50 + frac * 0.38, msg)

            classified = classify_images_batch(unique_images, progress_cb=_vision_prog)

            from utils.vision import INDEXABLE_TYPES

            # Only index technically useful image types — skip photos, logos, "other"
            technical = [img for img in classified if img["image_type"] in INDEXABLE_TYPES]
            skipped   = len(classified) - len(technical)
            if skipped:
                _prog(0.88, f"Skipped {skipped} non-technical image(s) (photos/logos)…")

            image_items = [
                {
                    "chunk_id": _stable_image_id(img["image_path"]),
                    "text":     img["description"],
                    "metadata": {
                        "chunk_type":  "image",
                        "source_pdf":  img["source_pdf"],
                        "page_number": img["page_number"],
                        "image_path":  img["image_path"],
                        "image_type":  img["image_type"],
                        "tags":        "",
                        "image_paths": json.dumps([img["image_path"]]),
                    },
                }
                for img in technical
            ]

            if image_items:
                _prog(0.88, f"Embedding {len(image_items)} image description(s)…")
                image_committed = _embed_and_upsert(
                    image_items, collection, voyage_client, progress_cb,
                    progress_start=0.88, progress_end=0.98,
                    label="Embedding image chunk",
                )

    _prog(1.0, f"Done — {text_committed} text + {image_committed} image chunks committed.")
    return {"text_chunks": text_committed, "image_chunks": image_committed}


# ── Read helpers (used by sidebar and Manuals tab) ────────────────────────────

def get_indexed_pdfs() -> list[dict]:
    """
    Return one entry per unique PDF in ChromaDB.
    Each entry: {source_pdf, text_chunks, image_chunks}
    """
    try:
        collection = _get_collection()
        results    = collection.get(include=["metadatas"])
        stats: dict[str, dict] = {}
        for meta in results["metadatas"]:
            name       = meta.get("source_pdf", "Unknown")
            chunk_type = meta.get("chunk_type", "text")
            if name not in stats:
                stats[name] = {"text_chunks": 0, "image_chunks": 0}
            if chunk_type == "image":
                stats[name]["image_chunks"] += 1
            else:
                stats[name]["text_chunks"] += 1
        return [
            {"source_pdf": k, **v}
            for k, v in sorted(stats.items())
        ]
    except Exception:
        return []


def delete_pdf_from_index(pdf_name: str) -> int:
    """Remove all chunks (text + image) for pdf_name. Returns count deleted."""
    collection = _get_collection()
    existing   = collection.get(where={"source_pdf": pdf_name}, include=[])
    ids        = existing["ids"]
    if ids:
        collection.delete(ids=ids)
    return len(ids)


def get_total_chunk_count() -> int:
    """Total chunks in ChromaDB (text + image)."""
    try:
        return _get_collection().count()
    except Exception:
        return 0
