[theme]
base                     = "dark"
primaryColor             = "#ff7849"
backgroundColor          = "#111113"
secondaryBackgroundColor = "#2c2c32"
textColor                = "#f0f0f2"
font                     = "sans serif"
